### ISSUE TITLE
Upgrade Angluar 2.0.0 to 2.4.1 causes issues.

### ISSUE THREAD

**Issue by DennisDel** [ceolter/ag-grid-ng2#111]
I upgraded Angular to 2.4.1 and I got following error.
![image](https://cloud.githubusercontent.com/assets/7200595/21624676/b0694d62-d253-11e6-9a83-ca79f2209c8a.png)
The version that I am using is "6.0.1".
I also upgraded ag-grid-ng2 to latest version (7.1.1) but still got following error.

EXEC(183,105): error TS2339: Property 'forRoot' does not exist on type 'typeof AgGridModule'.

**Comment by seanlandsman** [comment]
6.x is not compatible with 2.4 (or even 2.3) due to changes made in angular. If you want to use 2.4.x you'll need to use 7.x

For 7.x we had to make a number of changes for AOT compatiability - please see the docs for information (https://www.ag-grid.com/best-angular-2-data-grid/), but in a nutshell you need to use:

````
AgGridModule.withComponents(
        [...optional components...]
)
````

instead. Note too that support for template strings was dropped in 7.x (again to support AOT).
