### ISSUE TITLE
Uncaught ReferenceError: require is not defined(anonymous function) @ main.js:2 

### ISSUE THREAD

**Issue by otabekgb** [ceolter/ag-grid-ng2#3]
I setup my files, versions and configuration exactly like in https://github.com/ceolter/ag-grid-ng2-example, but I get following error in Chrome console:
main.js:2 Uncaught ReferenceError: require is not defined(anonymous function) @ main.js:2
Error: http://localhost:56789/node_modules/ag-grid-ng2/main.js did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support.(…)@ angular2-polyfills.js:1243

**Comment by nborelli** [comment]
I load ag-grid/dist/ag-grid.js and then ag-grid-ng2/lib/agGridNg2.js in my index.html file and this makes everything work for me.  However, I get the error you refer to when loading this same scripts in my karka.config.js file to setup my unit tests. It prevents the unit tests from running altogether. The top part of my Karma config looks like this:

```
'use strict';
module.exports = function(config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: './',


    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine'],


    // list of files / patterns to load in the browser
    files: [
      'node_modules/zone.js/dist/zone.js',
      'node_modules/zone.js/dist/long-stack-trace-zone.js',
      'node_modules/zone.js/dist/jasmine-patch.js',
      'node_modules/es6-module-loader/dist/es6-module-loader.js',
      'node_modules/traceur/bin/traceur-runtime.js', 
      'node_modules/traceur/bin/traceur.js',
      'node_modules/systemjs/dist/system.src.js',
      'node_modules/reflect-metadata/Reflect.js',
**      'node_modules/ag-grid/dist/ag-grid.js',
      'node_modules/ag-grid-ng2/lib/agGridNg2.js',**
```

**Comment by ceolter** [comment]
When it complains that require()  is missing, then something wrong with
your setup. Whatever you are using fir module loading (systemjs??) is not
making require available.

**Comment by nathanhokanson** [comment]
I am seeing the same error when trying to run tests.  We didn't see this error until including the ag-grid-ng2 in our project.  The problem we are seeing is that there is no dist folder in node_modules/ag-grid-ng2 that has the compiled js in it.  The agGridNg2.js in lib is not set up in a require consistent manner (wrapped in a function as detailed here:  http://requirejs.org/docs/errors.html#notloaded).

**Comment by seanlandsman** [comment]
@nborelli Hi Neal - is this still an issue for you? I'm cleaning up old issues and want to try resolve some of these long standing ones

**Comment by seanlandsman** [comment]
@nathanhokanson @nborelli I was able to reproduce this and find a fix

Add these to your karma.conf.js:

```
        plugins: [
            require('karma-systemjs'),
            require('karma-jasmine'),
           ...other plugins
        ],

        frameworks: ['systemjs', 'jasmine'],
```

**Comment by pdavin** [comment]
I'm encountering this issue on my karma config. I tried copying your karma config, but it didn't resolve it for me. 

The sample project has no Karma test files. It would help if you could add one unit test, like a very basic app.component test. Currently it's hard to see whether the sample project Karma run is actually working and doesn't have any runtime errors, since the 0 of 0 tests means not all app dependencies are being loaded. I turned on LOG_DEBUG and confirmed Karma isn't loading (serving) any ag-grid files, so it's hard to confirm whether the "require is not defined" issue isn't present. 

I tried adding a basic app.component test, but there's more config work needed than I expected (the webpack/ subproject doesn't load any test files in its karma-test-shim, so I guess only systemjs_aot is ready for karma tests... but that one I also was not able to make run my test).
