### ISSUE TITLE
Postinstall typings issue

### ISSUE THREAD

**Issue by DzmitryShylovich** [ceolter/ag-grid-ng2#32]
We no longer need typings in typescript 2.0 ([source](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/)). So [this](https://github.com/ceolter/ag-grid-ng2/blob/master/package.json#L8) line cause issues for typescript 2.0 users. I hope you can remove it.

**Comment by ceolter** [comment]
thanks for raising. will move to 2.0 in coming days.

**Comment by dan-madaket** [comment]
@DzmitryShylovich any workarounds for this short of cloning and removing in the near term?

**Comment by DzmitryShylovich** [comment]
@dan-madaket just add typings as a dev dependency

```
"devDependencies": {
    "typings": "1.3.3",
}
```

**Comment by BTMorton** [comment]
Do you have an ETA on when the postinstall will be removed? We currently have both ag-grid-ng2 and typings as a dev dependency, but get the error because the postinstall script seems to be running before typings is installed.

As a short-term fix until you move to typescript 2.0, could you either remove the postinstall (meaning a manual step when you build) or add typings as a full (not dev) dependency?

**Comment by seanlandsman** [comment]
We're working on this at the moment - we should have it done by next week

**Comment by a0a057** [comment]
is this still on track for a release this week?

**Comment by seanlandsman** [comment]
Yes! :-)

**Comment by seanlandsman** [comment]
latest release uses typescript 2 (and removes typings)
