### ISSUE TITLE
cellRenderer from Angular 2 Templates - refresh

### ISSUE THREAD

**Issue by moxival** [ceolter/ag-grid-ng2#77]
I cannot make the cell (using renderer from template) to use the updated row data. Every column that does not use cellRendererFramework with NG template is updating as it should. Is it not possible?

cellRendererFramework:
```
{
      template      : `{{params.value | date:'${format}'}}`,
      moduleImports : [ CommonModule ]
}
```

**Comment by moxival** [comment]
On a side note the very simple component works:

```
import { Component } from "@angular/core";
import { AgRendererComponent } from "ag-grid-ng2";

@Component({
  template : '{{value | date}}'
})
export class AgDateRenderComponent implements AgRendererComponent {
  protected value ;

  agInit(params: any) {
    this.value = params.value;
  }

  refresh(params: any): void {
    this.value = params.value;
  }
}
```

**Comment by seanlandsman** [comment]
Hi,

I'll take a look at this, but its worth noting that with ag-grid-ng2@7.x the facility to render with templates is being removed, so you may want to start using components going forward anyway.

Take a look at the beta documentation for more information: https://www.ag-grid.com/angular-2-beta-release/

**Comment by seanlandsman** [comment]
Hi @moxival 

We'll be releasing 7x next week and with it we'll  be removing support for templates strings. This cant be helped unfortunately, as in order to support AOT and dynamic components we can no longer dynamically create components which is what we were using for template strings.

Closing this as template string support will be dropped shortly
